### ISSUE TITLE
Compatibility with SMAPI

### ISSUE THREAD

**Issue by Drogean** [kevinmurphy678/Stardew_Injector#15]
https://github.com/Zoryn4163/SMAPI

Both seem to rely on using an .exe launcher to inject code into the game so they cannot be used at the same time.

Stardew Injector has some must have game fixes that are absolutely amazing

Perhaps a way to port over the time-scale, fishing bubbles, and run speed mods?

**Comment by kevinmurphy678** [comment]
I've tried to get it to work with SMAPI but wasn't able to. Stardew Injector modifies the assembly of the game and executes the modified assembly. If you point SMAPI to this modified assembly it will crash because SMAPI was created with reference to the original games assembly, not the modified version. 

I'm sure there's a way to get it to work but I'm not sure at the moment. I'll have to look into it

**Comment by OverlordCW** [comment]
Maybe it's possible to rewrite the injector into a mod dll that SMAPI can load instead?

**Comment by Zoryn4163** [comment]
I fully support the thought of having this made into a mod, but I will attempt to have the two EXEs work in tandem as well. I'll start looking into it on my end once I achieve what I am currently working on in SMAPI (Custom Items/Placeables)

**Comment by Drogean** [comment]
it looks like as of now, the run speed mod, time change mods, and instant fishing mod have now been ported over to SMAPI by the community

it looks like the only thing that needs to be ported is something that adds the "fish bubble hotspots" and the debugmenu
